In [11]:
import os
os.chdir('C:\\Users\\User\\Downloads')

In [10]:
import pandas as pd
import numpy as np

In [40]:
dataset = pd.read_csv('IRIS.csv')

In [36]:
dataset

Id  sepal_length  sepal_width  petal_length  petal_width         species
0      1           5.1          3.5           1.4          0.2     Iris-setosa
1      2           4.9          3.0           1.4          0.2     Iris-setosa
2      3           4.7          3.2           1.3          0.2     Iris-setosa
3      4           4.6          3.1           1.5          0.2     Iris-setosa
4      5           5.0          3.6           1.4          0.2     Iris-setosa
..   ...           ...          ...           ...          ...             ...
145  146           6.7          3.0           5.2          2.3  Iris-virginica
146  147           6.3          2.5           5.0          1.9  Iris-virginica
147  148           6.5          3.0           5.2          2.0  Iris-virginica
148  149           6.2          3.4           5.4          2.3  Iris-virginica
149  150           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 6 columns]

In [43]:
x = dataset.iloc[:,1:5].values

In [45]:
y = dataset.iloc[:,5].values

In [24]:
from sklearn.preprocessing import LabelEncoder
label_y = LabelEncoder()
y = label_y.fit_transform(y)

In [26]:
from sklearn.model_selection import train_test_split
X_train,X_test, y_train,y_test = train_test_split(x,y,test_size = 0.2)

# Logistic Regression


In [27]:
from sklearn.linear_model import LogisticRegression
logmodel = LogisticRegression()
logmodel.fit(X_train, y_train)

C:\Users\User\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [30]:
y_pred = logmodel.predict(X_test)
y_pred

array([2, 1, 1, 0, 2, 1, 0, 0, 2, 1, 2, 1, 1, 1, 0, 2, 2, 1, 2, 2, 2, 2,
       0, 1, 2, 1, 1, 1, 1, 2])

In [31]:
y_test

array([2, 1, 1, 0, 2, 1, 0, 0, 2, 1, 2, 1, 1, 1, 0, 2, 2, 1, 2, 2, 1, 2,
       0, 1, 2, 1, 1, 1, 1, 2])

In [33]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)
#Row-wise
#category 1 Iris Setosa 5 
#category 2 Iris Versi-color 14(13 correct 1 wrong)
#category 3 Iris Virginica 11

array([[ 5,  0,  0],
       [ 0, 13,  1],
       [ 0,  0, 11]], dtype=int64)

In [46]:
# model_accuracy = 
(5+13+11)/(5+13+1+11)

0.9666666666666667

# K Nearest Neighbours


In [48]:
from sklearn.neighbors import KNeighborsClassifier
class_knn = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2) # p =2 Euclidean distance and p =1 Manhattan Distance
class_knn.fit(X_train, y_train)

KNeighborsClassifier()

In [49]:
y_pred = class_knn.predict(X_test)

In [51]:
confusion_matrix(y_test, y_pred)

array([[ 5,  0,  0],
       [ 0, 12,  2],
       [ 0,  0, 11]], dtype=int64)

In [52]:
# model_accuracy = 
(5+12+11)/(5+12+2+11)

0.9333333333333333

# Naive Bayes


In [55]:
from sklearn.naive_bayes import GaussianNB
class_nb = GaussianNB()
class_nb.fit(X_train, y_train)

GaussianNB()

In [58]:
y_pred = class_nb.predict(X_test)

In [59]:
confusion_matrix(y_test, y_pred)

array([[ 5,  0,  0],
       [ 0, 14,  0],
       [ 0,  0, 11]], dtype=int64)

In [60]:
# model_accuracy = 
(5+14+11)/(5+14+11)

1.0

# Support Vector  Machine Alg.


In [62]:
from sklearn.svm import SVC
class_svm_sigmoid = SVC(kernel = 'sigmoid')
class_svm_sigmoid.fit(X_train, y_train)

SVC(kernel='sigmoid')

In [63]:
y_pred = class_svm_sigmoid.predict(X_test)

In [64]:
confusion_matrix(y_test, y_pred)

array([[ 5,  0,  0],
       [14,  0,  0],
       [11,  0,  0]], dtype=int64)

In [66]:
# model accuracy = 
5/(5+14+11)
#above the accuracy has gone way below as it is saying allflowers belongs to the same category

0.16666666666666666

In [67]:
from sklearn.svm import SVC
class_svm_linear = SVC(kernel = 'linear')
class_svm_linear.fit(X_train, y_train)

SVC(kernel='linear')

In [68]:
y_pred = class_svm_linear.predict(X_test)

In [69]:
confusion_matrix(y_test, y_pred)

array([[ 5,  0,  0],
       [ 0, 12,  2],
       [ 0,  0, 11]], dtype=int64)

In [70]:
# model accuracy = 
(5+12+11)/(5+12+11+2)

0.9333333333333333

In [71]:
from sklearn.svm import SVC
class_svm_rbf = SVC(kernel = 'rbf')
class_svm_rbf.fit(X_train, y_train)

SVC()

In [72]:
y_pred = class_svm_rbf.predict(X_test)

In [73]:
confusion_matrix(y_test, y_pred)

array([[ 5,  0,  0],
       [ 0, 13,  1],
       [ 0,  0, 11]], dtype=int64)

In [74]:
# model accuracy = 
(5+13+11)/(5+13+11+1)

0.9666666666666667

In [75]:
from sklearn.svm import SVC
class_svm_poly = SVC(kernel = 'poly')
class_svm_poly.fit(X_train, y_train)

SVC(kernel='poly')

In [76]:
y_pred = class_svm_poly.predict(X_test)

In [77]:
confusion_matrix(y_test, y_pred)

array([[ 5,  0,  0],
       [ 0, 12,  2],
       [ 0,  0, 11]], dtype=int64)

In [78]:
# model accuracy = 
(5+12+11)/(5+12+11+2)

0.9333333333333333

In [80]:
from sklearn.tree import DecisionTreeClassifier
class_dt = DecisionTreeClassifier(criterion = 'entropy')
class_dt.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy')

In [81]:
y_pred = class_dt.predict(X_test)

In [82]:
confusion_matrix(y_test, y_pred)

array([[ 5,  0,  0],
       [ 0, 13,  1],
       [ 0,  0, 11]], dtype=int64)

In [83]:
# model accuracy = 
(5+13+11)/(5+13+11+1)

0.9666666666666667

In [85]:
from sklearn.ensemble import RandomForestClassifier
classifier_rfc = RandomForestClassifier(n_estimators = 3, criterion = 'entropy')
classifier_rfc.fit(X_train,  y_train)

RandomForestClassifier(criterion='entropy', n_estimators=3)

In [86]:
y_pred = classifier_rfc.predict(X_test)

In [88]:
confusion_matrix(y_test, y_pred)

array([[ 5,  0,  0],
       [ 0, 13,  1],
       [ 0,  0, 11]], dtype=int64)

In [89]:
# model accuracy = 
(5+13+11)/(5+13+11+1)

0.9666666666666667